/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "devices.index": [],
    "devices.create": [],
    "devices.store": [],
    "devices.show": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "devices.edit": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "devices.update": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "devices.destroy": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "register": [],
    "register.store": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
